### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by thisismyname34** [gitgiggety/plugin.video.stash#10]
When launching the addon, it crashes immediately and a "Stash Kodi Plugin Error" message is shown and tells me that more information is in the log, this is whats there:
```
2023-05-04 20:03:26.103 T:4469    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: GraphQL query failed:500 - b'unauthorized\n'. Query: 
                                                   query findDefaultFilter($mode: FilterMode!) {
                                                       findDefaultFilter(mode: $mode) {
                                                           name
                                                           filter
                                                       }
                                                   }
                                                   . Variables: {'mode': 'SCENES'}
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/addon.py", line 4, in <module>
                                                       run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/plugin.py", line 27, in run
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/plugin.py", line 110, in router
                                                       browse_root()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/plugin.py", line 35, in browse_root
                                                       for (item, url) in listing.get_filters():
                                                                          ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/listing/listing.py", line 49, in get_filters
                                                       default_filter = self._client.find_default_filter(self._filter_type)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/stash_interface.py", line 363, in find_default_filter
                                                       result = self.__call_graphql(query, variables)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.stash/resources/lib/stash_interface.py", line 41, in __call_graphql
                                                       raise Exception(
                                                   Exception: GraphQL query failed:500 - b'unauthorized\n'. Query: 
                                                   query findDefaultFilter($mode: FilterMode!) {
                                                       findDefaultFilter(mode: $mode) {
                                                           name
                                                           filter
                                                       }
                                                   }
                                                   . Variables: {'mode': 'SCENES'}
                                                   -->End of Python script error report<--
                                                   
2023-05-04 20:03:26.241 T:4467    error <general>: GetDirectory - Error getting plugin://plugin.video.stash/
2023-05-04 20:03:26.248 T:1983    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.stash/) failed
```

This is on an Nvidia Shield

**Comment by feelfreetoblameme** [comment]
Seeing the same issue, Nvidia Shield Pro with latest version of Kodi Nexus.

**Comment by gitgiggety** [comment]
> GraphQL query failed:500 - b'unauthorized\n'.

I think you set up credentials in Stash? So you must create an API token in Stash as well, and provide this API token in the settings of the plugin. Otherwise the plugin can't authenticate to Stash and it is obviously impossible to access the contents of Stash.
